In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data.csv', delimiter = ';')
df.head(5)

,PERIODO,SES_DESRED,SES_DESCAS,DES_GRU,DES_ACT,DES_SER,CANTIDAD,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO,FECHA_CORTE
0,201501,AMAZONAS ...,EL BUEN SAMARITANO ...,Consulta Externa ...,Consultan Nuev ...,...,84,AMAZONAS,UTCUBAMBA,BAGUA GRANDE,10701,20230612
1,201501,AMAZONAS ...,EL BUEN SAMARITANO ...,Consulta Externa ...,Consultan.Estab ...,...,1972,AMAZONAS,UTCUBAMBA,BAGUA GRANDE,10701,20230612
2,201501,AMAZONAS ...,EL BUEN SAMARITANO ...,Consulta Externa ...,Consultan.Serv. ...,Cirugia ...,355,AMAZONAS,UTCUBAMBA,BAGUA GRANDE,10701,20230612
3,201501,AMAZONAS ...,EL BUEN SAMARITANO ...,Consulta Externa ...,Consultan.Serv. ...,Ginecologia ...,305,AMAZONAS,UTCUBAMBA,BAGUA GRANDE,10701,20230612
4,201501,AMAZONAS ...,EL BUEN SAMARITANO ...,Consulta Externa ...,Consultan.Serv. ...,Medicina ...,1619,AMAZONAS,UTCUBAMBA,BAGUA GRANDE,10701,20230612

In [3]:
print("Forma del dataframe:\n", df.shape, "\n")
print("Columnas del dataframe\n:", df.columns, "\n")
print("Tipos de datos de cada columna:\n", df.dtypes, "\n")

Forma del dataframe:
 (650755, 12)

Columnas del dataframe
: Index(['PERIODO', 'SES_DESRED', 'SES_DESCAS', 'DES_GRU', 'DES_ACT', 'DES_SER',
       'CANTIDAD', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'UBIGEO',
       'FECHA_CORTE'],
      dtype='str')

Tipos de datos de cada columna:
 PERIODO         int64
SES_DESRED        str
SES_DESCAS        str
DES_GRU           str
DES_ACT           str
DES_SER           str
CANTIDAD        int64
DEPARTAMENTO      str
PROVINCIA         str
DISTRITO          str
UBIGEO          int64
FECHA_CORTE     int64
dtype: object

In [4]:

print("Valores nulos por columna:\n", df.isnull().sum(), "\n")
print("Valores unicos:\n", df.nunique(), "\n")

Valores nulos por columna:
 PERIODO         0
SES_DESRED      0
SES_DESCAS      0
DES_GRU         0
DES_ACT         0
DES_SER         0
CANTIDAD        0
DEPARTAMENTO    0
PROVINCIA       0
DISTRITO        0
UBIGEO          0
FECHA_CORTE     0
dtype: int64

Valores unicos:
 PERIODO            96
SES_DESRED         65
SES_DESCAS        793
DES_GRU             2
DES_ACT            26
DES_SER            12
CANTIDAD        15177
DEPARTAMENTO       30
PROVINCIA         172
DISTRITO          327
UBIGEO            335
FECHA_CORTE         1
dtype: int64

In [5]:
df.groupby("DES_ACT")["CANTIDAD"].sum().sort_values(ascending=False).head(15)

DES_ACT
N.Cit. C. Ext                                                                                                                                             133011946
Consultas                                                                                                                                                 117665057
Consultan.Serv.                                                                                                                                            53296328
Consultan.Estab                                                                                                                                            33802838
Horas Prog.                                                                                                                                                27732924
Hras.Efec.(Eje)                                                                                                                                            25578665
N. Deser C.Ext                                                                                                                                             15704226
N.Cit. C. Ext                                                                                                                                              14710116
Consultas                                                                                                                                                  13480337
Consultan Nuev                                                                                                                                              9680801
Consultan.Serv.                                                                                                                                             5959149
Num.Pac.C.C.D.                                                                                                                                              5093488
Consultan.Estab                                                                                                                                             3446762
Horas Prog.                                                                                                                                                 3185683
Hras.Efec.(Eje)                                                                                                                                             2918742
Name: CANTIDAD, dtype: int64

In [6]:
for v in df["DES_ACT"].unique():
    print(repr(v))

'Consultan Nuev                                                                                                                                        '
'Consultan.Estab                                                                                                                                       '
'Consultan.Serv.                                                                                                                                       '
'Consultas                                                                                                                                             '
'Horas Prog.                                                                                                                                           '
'Hras.Efec.(Eje)                                                                                                                                       '
'N. Deser C.Ext                                                                                                                                        '
'N.Cit. C. Ext                                                                                                                                         '
'Nro.Cons.Fisico                                                                                                                                       '
'Nro.Cons.Funcio                                                                                                                                       '
'Nro.Medicos                                                                                                                                           '
'Num.P.N.C.D.                                                                                                                                          '
'Num.Pac.C.C.D.                                                                                                                                        '
'Num.Pac.Reing                                                                                                                                         '
'NÂºDÃ\xadas Prom.Dif                                                                                                                                       '
'Consultas'
'Consultan.Serv.'
'Nro.Cons.Funcio'
'Nro.Cons.Fisico'
'Consultan Nuev'
'Horas Prog.'
'Nro.Medicos'
'Hras.Efec.(Eje)'
'Consultan.Estab'
'N.Cit. C. Ext'
'N. Deser C.Ext'

In [7]:
print(df["DES_SER"].unique())

<StringArray>
['                                                  ',
 'Cirugia                                           ',
 'Ginecologia                                       ',
 'Medicina                                          ',
 'Pediatria                                         ',
 'Obstetricia                                       ',
                                        'Ginecologia',
                                           'Medicina',
                                            'Cirugia',
                                                  ' ',
                                          'Pediatria',
                                        'Obstetricia']
Length: 12, dtype: str

In [8]:
df["DES_SER"] = df["DES_SER"].str.strip()
df.groupby("DES_SER")["CANTIDAD"].sum().sort_values(ascending=False)

DES_SER
               219875357
Medicina       166066936
Cirugia         44561557
Pediatria       21579717
Ginecologia     18038401
Obstetricia       910421
Name: CANTIDAD, dtype: int64

In [9]:
df["DES_ACT"] = df["DES_ACT"].str.strip()
df.groupby("DES_ACT")["CANTIDAD"].sum().sort_values(ascending=False)

DES_ACT
N.Cit. C. Ext        147722062
Consultas            131145394
Consultan.Serv.       59255477
Consultan.Estab       37249600
Horas Prog.           30918607
Hras.Efec.(Eje)       28497407
N. Deser C.Ext        16971538
Consultan Nuev        10946920
Num.Pac.C.C.D.         5093488
Num.Pac.Reing          1486624
Nro.Medicos             710516
Num.P.N.C.D.            393353
Nro.Cons.Funcio         375272
Nro.Cons.Fisico         254359
NÂºDÃ­as Prom.Dif        11772
Name: CANTIDAD, dtype: int64

In [41]:
df[df["DES_SER"] != ""].groupby("DES_ACT")["CANTIDAD"].sum().sort_values(ascending=False)

DES_ACT
Consultas          131145394
Consultan.Serv.     59255477
Horas Prog.         30918607
Hras.Efec.(Eje)     28497407
Nro.Medicos           710516
Nro.Cons.Funcio       375272
Nro.Cons.Fisico       254359
Name: CANTIDAD, dtype: int64

In [49]:
df[df["DES_ACT"] == "Hras.Efec.(Eje)"].groupby("DES_SER")["CANTIDAD"].sum().sort_values(ascending=False)

DES_SER
Medicina       18922445
Cirugia         4897969
Pediatria       2453550
Ginecologia     2085254
Obstetricia      138189
Name: CANTIDAD, dtype: int64

In [45]:
df[df["DES_ACT"] == "Horas Prog."].groupby("DES_SER")["CANTIDAD"].sum().sort_values(ascending=False)

DES_SER
Medicina       20545883
Cirugia         5277820
Pediatria       2658148
Ginecologia     2284967
Obstetricia      151789
Name: CANTIDAD, dtype: int64

In [64]:
df_horas = df[df["DES_ACT"].isin(["Horas Prog.", "Hras.Efec.(Eje)"])]
df_tabla = df_horas.groupby(["DES_SER","DES_ACT"])["CANTIDAD"].sum()
df_tabla = df_tabla.unstack()
df_tabla["hr_no_ejecutada"] = df_tabla["Horas Prog."] - df_tabla["Hras.Efec.(Eje)"]
df_tabla["tasa_no_cumplimiento"] = (df_tabla["hr_no_ejecutada"] / df_tabla["Horas Prog."])*100
df_tabla.sort_values(by="tasa_no_cumplimiento", ascending= False)

DES_ACT,Horas Prog.,Hras.Efec.(Eje),hr_no_ejecutada,tasa_no_cumplimiento
DES_SER,,,,
Obstetricia,151789,138189,13600,8.959806
Ginecologia,2284967,2085254,199713,8.740301
Medicina,20545883,18922445,1623438,7.901525
Pediatria,2658148,2453550,204598,7.697013
Cirugia,5277820,4897969,379851,7.197119