In [131]:
import pandas as pd
import numpy as np

In [132]:
df = pd.read_csv('data.csv', delimiter = ';')
df.head(5)

,PERIODO,SES_DESRED,SES_DESCAS,DES_GRU,DES_ACT,DES_SER,CANTIDAD,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO,FECHA_CORTE
0,201501,AMAZONAS ...,EL BUEN SAMARITANO ...,Consulta Externa ...,Consultan Nuev ...,...,84,AMAZONAS,UTCUBAMBA,BAGUA GRANDE,10701,20230612
1,201501,AMAZONAS ...,EL BUEN SAMARITANO ...,Consulta Externa ...,Consultan.Estab ...,...,1972,AMAZONAS,UTCUBAMBA,BAGUA GRANDE,10701,20230612
2,201501,AMAZONAS ...,EL BUEN SAMARITANO ...,Consulta Externa ...,Consultan.Serv. ...,Cirugia ...,355,AMAZONAS,UTCUBAMBA,BAGUA GRANDE,10701,20230612
3,201501,AMAZONAS ...,EL BUEN SAMARITANO ...,Consulta Externa ...,Consultan.Serv. ...,Ginecologia ...,305,AMAZONAS,UTCUBAMBA,BAGUA GRANDE,10701,20230612
4,201501,AMAZONAS ...,EL BUEN SAMARITANO ...,Consulta Externa ...,Consultan.Serv. ...,Medicina ...,1619,AMAZONAS,UTCUBAMBA,BAGUA GRANDE,10701,20230612

In [133]:
print("Forma del dataframe:\n", df.shape, "\n")
print("Columnas del dataframe\n:", df.columns, "\n")
print("Tipos de datos de cada columna:\n", df.dtypes, "\n")

Forma del dataframe:
 (650755, 12)

Columnas del dataframe
: Index(['PERIODO', 'SES_DESRED', 'SES_DESCAS', 'DES_GRU', 'DES_ACT', 'DES_SER',
       'CANTIDAD', 'DEPARTAMENTO', 'PROVINCIA', 'DISTRITO', 'UBIGEO',
       'FECHA_CORTE'],
      dtype='str')

Tipos de datos de cada columna:
 PERIODO         int64
SES_DESRED        str
SES_DESCAS        str
DES_GRU           str
DES_ACT           str
DES_SER           str
CANTIDAD        int64
DEPARTAMENTO      str
PROVINCIA         str
DISTRITO          str
UBIGEO          int64
FECHA_CORTE     int64
dtype: object

In [134]:

print("Valores nulos por columna:\n", df.isnull().sum(), "\n")
print("Valores unicos:\n", df.nunique(), "\n")

Valores nulos por columna:
 PERIODO         0
SES_DESRED      0
SES_DESCAS      0
DES_GRU         0
DES_ACT         0
DES_SER         0
CANTIDAD        0
DEPARTAMENTO    0
PROVINCIA       0
DISTRITO        0
UBIGEO          0
FECHA_CORTE     0
dtype: int64

Valores unicos:
 PERIODO            96
SES_DESRED         65
SES_DESCAS        793
DES_GRU             2
DES_ACT            26
DES_SER            12
CANTIDAD        15177
DEPARTAMENTO       30
PROVINCIA         172
DISTRITO          327
UBIGEO            335
FECHA_CORTE         1
dtype: int64

In [135]:
df.groupby("DES_ACT")["CANTIDAD"].sum().sort_values(ascending=False).head(15)

DES_ACT
N.Cit. C. Ext                                                                                                                                             133011946
Consultas                                                                                                                                                 117665057
Consultan.Serv.                                                                                                                                            53296328
Consultan.Estab                                                                                                                                            33802838
Horas Prog.                                                                                                                                                27732924
Hras.Efec.(Eje)                                                                                                                                            25578665
N. Deser C.Ext                                                                                                                                             15704226
N.Cit. C. Ext                                                                                                                                              14710116
Consultas                                                                                                                                                  13480337
Consultan Nuev                                                                                                                                              9680801
Consultan.Serv.                                                                                                                                             5959149
Num.Pac.C.C.D.                                                                                                                                              5093488
Consultan.Estab                                                                                                                                             3446762
Horas Prog.                                                                                                                                                 3185683
Hras.Efec.(Eje)                                                                                                                                             2918742
Name: CANTIDAD, dtype: int64

In [136]:
for v in df["DES_ACT"].unique():
    print(repr(v))

'Consultan Nuev                                                                                                                                        '
'Consultan.Estab                                                                                                                                       '
'Consultan.Serv.                                                                                                                                       '
'Consultas                                                                                                                                             '
'Horas Prog.                                                                                                                                           '
'Hras.Efec.(Eje)                                                                                                                                       '
'N. Deser C.Ext                                                                                                                                        '
'N.Cit. C. Ext                                                                                                                                         '
'Nro.Cons.Fisico                                                                                                                                       '
'Nro.Cons.Funcio                                                                                                                                       '
'Nro.Medicos                                                                                                                                           '
'Num.P.N.C.D.                                                                                                                                          '
'Num.Pac.C.C.D.                                                                                                                                        '
'Num.Pac.Reing                                                                                                                                         '
'NÂºDÃ\xadas Prom.Dif                                                                                                                                       '
'Consultas'
'Consultan.Serv.'
'Nro.Cons.Funcio'
'Nro.Cons.Fisico'
'Consultan Nuev'
'Horas Prog.'
'Nro.Medicos'
'Hras.Efec.(Eje)'
'Consultan.Estab'
'N.Cit. C. Ext'
'N. Deser C.Ext'

In [137]:
print(df["DES_SER"].unique())

<StringArray>
['                                                  ',
 'Cirugia                                           ',
 'Ginecologia                                       ',
 'Medicina                                          ',
 'Pediatria                                         ',
 'Obstetricia                                       ',
                                        'Ginecologia',
                                           'Medicina',
                                            'Cirugia',
                                                  ' ',
                                          'Pediatria',
                                        'Obstetricia']
Length: 12, dtype: str

In [138]:
df["DES_SER"] = df["DES_SER"].str.strip()
df.groupby("DES_SER")["CANTIDAD"].sum().sort_values(ascending=False)

DES_SER
               219875357
Medicina       166066936
Cirugia         44561557
Pediatria       21579717
Ginecologia     18038401
Obstetricia       910421
Name: CANTIDAD, dtype: int64

In [139]:
df["DES_ACT"] = df["DES_ACT"].str.strip()
df.groupby("DES_ACT")["CANTIDAD"].sum().sort_values(ascending=False)

DES_ACT
N.Cit. C. Ext        147722062
Consultas            131145394
Consultan.Serv.       59255477
Consultan.Estab       37249600
Horas Prog.           30918607
Hras.Efec.(Eje)       28497407
N. Deser C.Ext        16971538
Consultan Nuev        10946920
Num.Pac.C.C.D.         5093488
Num.Pac.Reing          1486624
Nro.Medicos             710516
Num.P.N.C.D.            393353
Nro.Cons.Funcio         375272
Nro.Cons.Fisico         254359
NÂºDÃ­as Prom.Dif        11772
Name: CANTIDAD, dtype: int64

In [140]:
df[df["DES_SER"] != ""].groupby("DES_ACT")["CANTIDAD"].sum().sort_values(ascending=False)

DES_ACT
Consultas          131145394
Consultan.Serv.     59255477
Horas Prog.         30918607
Hras.Efec.(Eje)     28497407
Nro.Medicos           710516
Nro.Cons.Funcio       375272
Nro.Cons.Fisico       254359
Name: CANTIDAD, dtype: int64

In [141]:
df[df["DES_ACT"] == "Hras.Efec.(Eje)"].groupby("DES_SER")["CANTIDAD"].sum().sort_values(ascending=False)

DES_SER
Medicina       18922445
Cirugia         4897969
Pediatria       2453550
Ginecologia     2085254
Obstetricia      138189
Name: CANTIDAD, dtype: int64

In [142]:
df[df["DES_ACT"] == "Horas Prog."].groupby("DES_SER")["CANTIDAD"].sum().sort_values(ascending=False)

DES_SER
Medicina       20545883
Cirugia         5277820
Pediatria       2658148
Ginecologia     2284967
Obstetricia      151789
Name: CANTIDAD, dtype: int64

In [143]:
df_horas = df[df["DES_ACT"].isin(["Horas Prog.", "Hras.Efec.(Eje)"])]
df_tabla = df_horas.groupby(["DES_SER","DES_ACT"])["CANTIDAD"].sum()
df_tabla = df_tabla.unstack()
df_tabla["hr_no_ejecutada"] = df_tabla["Horas Prog."] - df_tabla["Hras.Efec.(Eje)"]
df_tabla["tasa_no_cumplimiento"] = (df_tabla["hr_no_ejecutada"] / df_tabla["Horas Prog."])*100
df_tabla.sort_values(by="tasa_no_cumplimiento", ascending= False)

DES_ACT,Horas Prog.,Hras.Efec.(Eje),hr_no_ejecutada,tasa_no_cumplimiento
DES_SER,,,,
Obstetricia,151789,138189,13600,8.959806
Ginecologia,2284967,2085254,199713,8.740301
Medicina,20545883,18922445,1623438,7.901525
Pediatria,2658148,2453550,204598,7.697013
Cirugia,5277820,4897969,379851,7.197119

In [154]:
df["DEPARTAMENTO"].unique()

<StringArray>
[     'AMAZONAS',        'ANCASH',      'APURÍMAC',      'APURIMAC',
      'AREQUIPA',      'AYACUCHO',     'CAJAMARCA',   'LA LIBERTAD',
          'LIMA',         'CUSCO',         'PASCO', 'MADRE DE DIOS',
  'HUANCAVELICA',       'HUANUCO',    'SAN MARTIN',           'ICA',
          'PUNO',         'JUNÍN',         'JUNIN',    'LAMBAYEQUE',
        'LORETO',      'MOQUEGUA',    'SAN MARTÍN',         'PIURA',
        'CALLAO',         'TACNA',        'TUMBES',       'UCAYALI']
Length: 28, dtype: str

In [ ]:

df_prov_aza = df[df["PROVINCIA"]=="AZANGARO"]
df_prov_aza["DEPARTAMENTO"]=="AZANGARO"

2439      False
2440       True
2441       True
2442       True
2443       True
          ...
649923     True
649924     True
649925     True
649926     True
649927     True
Name: DEPARTAMENTO, Length: 1143, dtype: bool

In [146]:
df.loc[df["DEPARTAMENTO"]== "AZANGARO","DEPARTAMENTO"] = "PUNO"
df.loc[df["DEPARTAMENTO"]== "AZANGARO","DEPARTAMENTO"] == "PUNO"

Series([], Name: DEPARTAMENTO, dtype: bool)

In [155]:
df.loc[df["DEPARTAMENTO"]== "LIMA ","DEPARTAMENTO"] = "LIMA"
df.loc[df["DEPARTAMENTO"]=="APURÍMAC", "DEPARTAMENTO"] = "APURIMAC"
df.loc[df["DEPARTAMENTO"]=="JUNÍN", "DEPARTAMENTO"] = "JUNIN"
df.loc[df["DEPARTAMENTO"]=="SAN MARTÍN", "DEPARTAMENTO"] = "SAN MARTIN"

In [156]:
df["DEPARTAMENTO"].unique()

<StringArray>
[     'AMAZONAS',        'ANCASH',      'APURIMAC',      'AREQUIPA',
      'AYACUCHO',     'CAJAMARCA',   'LA LIBERTAD',          'LIMA',
         'CUSCO',         'PASCO', 'MADRE DE DIOS',  'HUANCAVELICA',
       'HUANUCO',    'SAN MARTIN',           'ICA',          'PUNO',
         'JUNIN',    'LAMBAYEQUE',        'LORETO',      'MOQUEGUA',
         'PIURA',        'CALLAO',         'TACNA',        'TUMBES',
       'UCAYALI']
Length: 25, dtype: str

In [166]:
df_horas = df[df["DES_ACT"].isin(["Horas Prog.", "Hras.Efec.(Eje)"])]
df_tabla_dep = df_horas.groupby(["DEPARTAMENTO","DES_ACT"])["CANTIDAD"].sum()
df_tabla_dep = df_tabla_dep.unstack()
df_tabla_dep["hr_no_ejecutada"] = df_tabla_dep["Horas Prog."] - df_tabla_dep["Hras.Efec.(Eje)"]
df_tabla_dep["tasa_no_cumplimiento"] = (df_tabla_dep["hr_no_ejecutada"] / df_tabla_dep["Horas Prog."])*100
df_tabla_dep.sort_values(by="tasa_no_cumplimiento", ascending= False)

DES_ACT,Horas Prog.,Hras.Efec.(Eje),hr_no_ejecutada,tasa_no_cumplimiento
DEPARTAMENTO,,,,
AMAZONAS,213218,176295,36923,17.317018
LAMBAYEQUE,1534727,1318711,216016,14.075207
AYACUCHO,302053,261840,40213,13.313226
MADRE DE DIOS,112867,97909,14958,13.252767
CAJAMARCA,551310,485133,66177,12.003591
UCAYALI,453565,413259,40306,8.886488
LIMA,12842463,11731016,1111447,8.654469
CALLAO,2709438,2482613,226825,8.371662
HUANUCO,471372,434641,36731,7.792359
AREQUIPA,2072701,1927447,145254,7.007957
PASCO,353666,328943,24723,6.990494
MOQUEGUA,315026,293080,21946,6.966409
PIURA,1303195,1222228,80967,6.212961
LA LIBERTAD,1777412,1670598,106814,6.009524
LORETO,547350,515085,32265,5.894766
APURIMAC,289501,275314,14187,4.900501
JUNIN,885876,843586,42290,4.773806
CUSCO,480478,457542,22936,4.773580
TUMBES,191896,182824,9072,4.727561
ICA,930009,886880,43129,4.637482
TACNA,416804,400803,16001,3.838975
SAN MARTIN,437856,421224,16632,3.798509
HUANCAVELICA,212911,205242,7669,3.601975
PUNO,679171,656971,22200,3.268691
ANCASH,833742,808223,25519,3.060779

In [167]:
df["PERIODO"].unique()

array([201501, 201502, 201503, 201504, 201505, 201506, 201507, 201508,
       201509, 201510, 201511, 201512, 201601, 201602, 201603, 201604,
       201605, 201606, 201607, 201608, 201609, 201610, 201611, 201612,
       201701, 201702, 201703, 201704, 201705, 201706, 201707, 201708,
       201709, 201710, 201711, 201712, 201801, 201802, 201803, 201804,
       201805, 201806, 201807, 201808, 201809, 201810, 201811, 201812,
       201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908,
       201909, 201910, 201911, 201912, 202001, 202002, 202003, 202004,
       202005, 202006, 202007, 202008, 202009, 202010, 202011, 202012,
       202101, 202102, 202103, 202104, 202105, 202106, 202107, 202108,
       202109, 202110, 202111, 202112, 202201, 202202, 202203, 202204,
       202205, 202206, 202207, 202208, 202209, 202210, 202211, 202212])

In [174]:
deps = [
    "AMAZONAS", "LAMBAYEQUE", "AYACUCHO", "MADRE DE DIOS", "CAJAMARCA",
    "UCAYALI", "LIMA", "CALLAO", "HUANUCO", "AREQUIPA",
    "PASCO", "MOQUEGUA", "PIURA", "LA LIBERTAD", "LORETO",
]
df_horas = df[df["DES_ACT"].isin(["Horas Prog.", "Hras.Efec.(Eje)"])]
df_horas_filt = df_horas[df_horas["DEPARTAMENTO"].isin(deps)]
df_horas_filt["PERIODO_AÑO"] = (df_horas_filt["PERIODO"]//100)
df_tabla_per = df_horas_filt.groupby(["DEPARTAMENTO","PERIODO_AÑO","DES_ACT"])["CANTIDAD"].sum()
df_tabla_per = df_tabla_per.unstack()
df_tabla_per["hr_no_ejecutada"] = df_tabla_per["Horas Prog."] - df_tabla_per["Hras.Efec.(Eje)"]
df_tabla_per["tasa_no_cumplimiento"] = (df_tabla_per["hr_no_ejecutada"] / df_tabla_per["Horas Prog."])*100
df_tabla_per

DES_ACT                   Horas Prog.  Hras.Efec.(Eje)  hr_no_ejecutada  \
DEPARTAMENTO PERIODO_AÑO
AMAZONAS     2015               29885            26590             3295
             2016               32151            28107             4044
             2017               32809            28008             4801
             2018               36223            30887             5336
             2019               33842            28638             5204
...                               ...              ...              ...
UCAYALI      2018               67885            64861             3024
             2019               77956            71843             6113
             2020               33458            24557             8901
             2021               31902            25604             6298
             2022               63355            57662             5693

DES_ACT                   tasa_no_cumplimiento
DEPARTAMENTO PERIODO_AÑO
AMAZONAS     2015                    11.025598
             2016                    12.578147
             2017                    14.633180
             2018                    14.730972
             2019                    15.377342
...                                        ...
UCAYALI      2018                     4.454592
             2019                     7.841603
             2020                    26.603503
             2021                    19.741709
             2022                     8.985873

[120 rows x 4 columns]

In [180]:
pos_alta = df_tabla_per.groupby("DEPARTAMENTO")["tasa_no_cumplimiento"].idxmax()
df_tabla_per.loc[pos_alta].sort_values(by= "tasa_no_cumplimiento", ascending=False)

,DES_ACT,Horas Prog.,Hras.Efec.(Eje),hr_no_ejecutada,tasa_no_cumplimiento
DEPARTAMENTO,PERIODO_AÑO,,,,
LAMBAYEQUE,2021,118027,51173,66854,56.642972
CALLAO,2020,293550,134287,159263,54.254130
AMAZONAS,2021,7415,4675,2740,36.952124
LIMA,2020,1043260,672194,371066,35.567931
AREQUIPA,2020,127479,91047,36432,28.578825
AYACUCHO,2020,26521,18984,7537,28.418989
UCAYALI,2020,33458,24557,8901,26.603503
MADRE DE DIOS,2021,2984,2221,763,25.569705
LA LIBERTAD,2021,68084,50720,17364,25.503789
MOQUEGUA,2021,9123,6810,2313,25.353502
CAJAMARCA,2020,40226,32092,8134,20.220753
PASCO,2020,20787,16810,3977,19.132150
HUANUCO,2021,20464,16747,3717,18.163604
PIURA,2020,94889,78015,16874,17.782883
LORETO,2021,40597,35460,5137,12.653644

In [179]:
pos_baja = df_tabla_per.groupby("DEPARTAMENTO")["tasa_no_cumplimiento"].idxmin()
df_tabla_per.loc[pos_baja].sort_values(by= "tasa_no_cumplimiento", ascending=False)

,DES_ACT,Horas Prog.,Hras.Efec.(Eje),hr_no_ejecutada,tasa_no_cumplimiento
DEPARTAMENTO,PERIODO_AÑO,,,,
AMAZONAS,2015,29885,26590,3295,11.025598
CAJAMARCA,2019,83516,76655,6861,8.215192
MADRE DE DIOS,2018,18990,17648,1342,7.066877
AYACUCHO,2018,43815,41447,2368,5.404542
HUANUCO,2019,73683,70070,3613,4.903438
LIMA,2018,1910782,1817708,93074,4.870990
LORETO,2016,74515,71175,3340,4.482319
UCAYALI,2018,67885,64861,3024,4.454592
LAMBAYEQUE,2016,217002,207353,9649,4.446503
PIURA,2022,182210,176420,5790,3.177652
MOQUEGUA,2017,48301,46820,1481,3.066189
LA LIBERTAD,2018,296335,288657,7678,2.590987
CALLAO,2022,192697,188221,4476,2.322818
PASCO,2015,54322,53129,1193,2.196164
AREQUIPA,2017,309233,303636,5597,1.809962